"""
Given a text and a list of entities (post NER) find all connections between them
"""
from config import STAGE, combinations
from utils import get_ents_from_doc, pairwise


def alias_resolution(list):
    if any(list):
        return list[0]
    else:
        return None


def family_links(entity_list, connection_list):
    """
    family connections by surname \n
    :return: List of connected entities by surname
    """

    for subset in combinations(entity_list, 2):
        name1 = str(subset[0][0]).split(" ")
        name2 = str(subset[1][0]).split(" ")
        if len(name1) > 1 and len(name2) > 1 and name1[1] == name2[1]:
            connection_list.append([subset[0], subset[1], 1])

    return connection_list


def link_entities(connection_list, entity1, entity):
    """
    Creates link betweeen two entities if conditions apply
    :returns: new link list
    """
    if entity1 != entity:
        found = False
        for link in connection_list:
            a = False
            b = False
            for i, ent in enumerate(link):
                if i != 2 and entity1 == ent:
                    a = True
                if i != 2 and entity == ent:
                    b = True
            if a and b:
                link[2] += 1
                found = True

        if not found:
            connection_list.append([entity1, entity, 1])

    return connection_list


def entity_links(entity_list, parsed_list):
    """
    Two entities are considered to have a link if they appear in a range of two consecutive sentences.
    :return: a list of tuples
    """
    if STAGE == 2:
        connection_list = []
        # connection_list = family_links(entity_list, connection_list)
        for pair in pairwise(parsed_list):
            ents_list = get_ents_from_doc(pair[0]) + get_ents_from_doc(pair[1])
            if any(ents_list):
                # get list of person entities from ents_list
                candidates = []
                for ent in ents_list:
                    candidates += [x for x in entity_list for w in x if w == ent]
                for a, b in combinations(candidates, 2):
                    connection_list = link_entities(connection_list, a, b)
    else:
        connection_list = [[['Hari Seldon'], ['Gaal Dornick'], 52],
                           [['Encyclopedia Foundation'], ['Gaal Dornick'], 1],
                           [['Galactic Empire'], ['Gaal Dornick'], 3],
                           [['Hari Seldon'], ['Raven Seldon'], 8],
                           [['Avakim'], ['Hari Seldon'], 3],
                           [['Avakim'], ['Gaal Dornick'], 4],
                           [['Linge Chen'], ['Gaal Dornick'], 5],
                           [['Hari Seldon'], ['Advocate'], 3],
                           [['Advocate'], ['Galactic Empire'], 1],
                           [['Hari Seldon'], ['Galactic Empire'], 63],
                           [['Second Empire'], ['Galactic Empire'], 31],
                           [['Linge Chen'], ['Hari Seldon'], 5],
                           [['Hari Seldon'], ['Fie'], 12],
                           [['Fie'], ['Gaal Dornick'], 2],
                           [['Salvor Hardin'], ['Pirenne'], 31],
                           [['Pirenne'], ['Fie'], 1],
                           [['Fie'], ['Salvor Hardin'], 3],
                           [['Pirenne'], ['First Foundation'], 5],
                           [['First Foundation'], ['Encyclopedia Foundation'], 18],
                           [['Salvor Hardin'], ['First Foundation'], 39],
                           [['Pirenne'], ['Encyclopedia Foundation'], 3],
                           [['Yate Fulham'], ['Pirenne'], 2],
                           [['Pirenne'], ['Jord Fara'], 2],
                           [['Jord Fara'], ['Jorane Sutt'], 2],
                           [['Jorane Sutt'], ['Yate Fulham'], 2],
                           [['Yate Fulham'], ['Jord Fara'], 4],
                           [['Yate Fulham'], ['Tomaz Sutt'], 2],
                           [['Galactic Empire'], ['Salvor Hardin'], 9],
                           [['Pirenne'], ['Dorwin'], 6],
                           [['Dorwin'], ['Jorane Sutt'], 1],
                           [['Jorane Sutt'], ['Tomaz Sutt'], 2],
                           [['Jorane Sutt'], ['Encyclopedia Foundation'], 2],
                           [['Encyclopedia Foundation'], ['Salvor Hardin'], 5],
                           [['Hari Seldon'], ['Jord Fara'], 10],
                           [['Salvor Hardin'], ['Jord Fara'], 9],
                           [['First Foundation'], ['Hari Seldon'], 104],
                           [['Salvor Hardin'], ['Dorwin'], 10],
                           [['Dorwin'], ['Encyclopedia Foundation'], 1],
                           [['Salvor Hardin'], ['Lameth'], 1],
                           [['Pirenne'], ['Lewis Bort'], 2],
                           [['Lewis Bort'], ['Encyclopedia Foundation'], 2],
                           [['Galactic Empire'], ['Dorwin'], 2],
                           [['Galactic Empire'], ['Jorane Sutt'], 1],
                           [['Jorane Sutt'], ['Salvor Hardin'], 6],
                           [['Salvor Hardin'], ['Yate Fulham'], 2],
                           [['Yate Fulham'], ['Encyclopedia Foundation'], 1],
                           [['Hari Seldon'], ['Salvor Hardin'], 29],
                           [['Lee Senter'], ['Yohan Lee'], 10],
                           [['Lee Senter'], ['Encyclopedia Foundation'], 2],
                           [['Hari Seldon'], ['Encyclopedia Foundation'], 5],
                           [['Galactic Empire'], ['First Foundation'], 72],
                           [['Galactic Empire'], ['First Empire'], 16],
                           [['Yohan Lee'], ['Salvor Hardin'], 6],
                           [['Salvor Hardin'], ['Lee Senter'], 21],
                           [['First Foundation'], ['Lee Senter'], 2],
                           [['Lee Senter'], ['Sef Sermak'], 10],
                           [['Sef Sermak'], ['Salvor Hardin'], 19],
                           [['Encyclopedia Foundation'], ['Sef Sermak'], 2],
                           [['Poly Verisof'], ['First Foundation'], 6],
                           [['Salvor Hardin'], ['Poly Verisof'], 17],
                           [['Wienis'], ['Lepold I'], 10],
                           [['First Foundation'], ['Wienis'], 9],
                           [['Hari Seldon'], ['Plan'], 70],
                           [['Hari Seldon'], ['Poly Verisof'], 1],
                           [['Galactic Empire'], ['Poly Verisof'], 1],
                           [['Poly Verisof'], ['Lee Senter'], 1],
                           [['Lee Senter'], ['Hari Seldon'], 4],
                           [['Hari Seldon'], ['Yohan Lee'], 2],
                           [['Plan'], ['Poly Verisof'], 1],
                           [['Lepold I'], ['First Foundation'], 8],
                           [['Lepold I'], ['Hari Seldon'], 3],
                           [['Wienis'], ['Salvor Hardin'], 27],
                           [['Salvor Hardin'], ['Lepold I'], 8],
                           [['Lepold I'], ['Galactic Empire'], 3],
                           [['Lewis Bort'], ['Sef Sermak'], 10],
                           [['Lewis Bort'], ['Walto'], 3],
                           [['Lewis Bort'], ['First Foundation'], 5],
                           [['Walto'], ['Salvor Hardin'], 1],
                           [['Orsy'], ['Poly Verisof'], 2],
                           [['Salvor Hardin'], ['Lewis Bort'], 1],
                           [['Orsy'], ['Salvor Hardin'], 2],
                           [['Wienis'], ['Sef Sermak'], 2],
                           [['Sef Sermak'], ['First Foundation'], 2],
                           [['First Foundation'], ['Orsy'], 1],
                           [['Orsy'], ['Lewis Bort'], 1],
                           [['Lepold I'], ['Poly Verisof'], 1],
                           [['Theo Aporat'], ['Wienis'], 5],
                           [['Theo Aporat'], ['Fie'], 1],
                           [['Hari Seldon'], ['Sef Sermak'], 2],
                           [['Plan'], ['First Foundation'], 18],
                           [['Limmar Ponyets'], ['Eskel Gorov'], 7],
                           [['Limmar Ponyets'], ['First Foundation'], 2],
                           [['First Foundation'], ['Eskel Gorov'], 3],
                           [['Eskel Gorov'], ['Master Trader'], 2],
                           [['Master Trader'], ['Limmar Ponyets'], 2],
                           [['Galactic Empire'], ['Eskel Gorov'], 2],
                           [['Limmar Ponyets'], ['Grand Master'], 5],
                           [['Eskel Gorov'], ['Grand Master'], 4],
                           [['Grand Master'], ['Fie'], 1],
                           [['Grand Master'], ['Pherl'], 11],
                           [['Pherl'], ['Elders'], 2],
                           [['Pherl'], ['Eskel Gorov'], 1],
                           [['Limmar Ponyets'], ['Salvor Hardin'], 1],
                           [['Hober Mallow'], ['Jorane Sutt'], 33],
                           [['Jorane Sutt'], ['Hari Seldon'], 7],
                           [['Hari Seldon'], ['Hober Mallow'], 13],
                           [['Hober Mallow'], ['Master Trader'], 6],
                           [['Hober Mallow'], ['First Foundation'], 33],
                           [['Jorane Sutt'], ['First Foundation'], 6],
                           [['Hari Seldon'], ['Seldon Crisis'], 8],
                           [['Hober Mallow'], ['Galactic Empire'], 3],
                           [['First Foundation'], ['Second Empire'], 6],
                           [['Hober Mallow'], ['Fie'], 6],
                           [['Jord Fara'], ['First Foundation'], 3],
                           [['Hober Mallow'], ['Jord Fara'], 2],
                           [['Hober Mallow'], ['Trader Mallow'], 4],
                           [['First Foundation'], ['Grand Master'], 2],
                           [['Encyclopedia Foundation'], ['Galactic Empire'], 3],
                           [['First Foundation'], ['Personal Capsule'], 2],
                           [['Onum Barr'], ['Galactic Empire'], 16],
                           [['Hober Mallow'], ['Onum Barr'], 6],
                           [['Master Trader'], ['First Foundation'], 4],
                           [['Hober Mallow'], ['Ankor Jael'], 30],
                           [['Salvor Hardin'], ['Hober Mallow'], 24],
                           [['Ankor Jael'], ['Salvor Hardin'], 1],
                           [['Hari Seldon'], ['Ankor Jael'], 1],
                           [['Hober Mallow'], ['Flober Mallow'], 4],
                           [['Jorane Sutt'], ['Ankor Jael'], 3],
                           [['Galactic Empire'], ['Bel Riose'], 12],
                           [['Ducem Barr'], ['Onum Barr'], 61],
                           [['Bel Riose'], ['Ducem Barr'], 3],
                           [['Bel Riose'], ['Onum Barr'], 12],
                           [['Hari Seldon'], ['Bel Riose'], 10],
                           [['Bel Riose'], ['First Foundation'], 11],
                           [['Hober Mallow'], ['Sennett Forell'], 5],
                           [['Sennett Forell'], ['Fie'], 1],
                           [['Sennett Forell'], ['Galactic Empire'], 3],
                           [['Second Empire'], ['Hari Seldon'], 7],
                           [['Sennett Forell'], ['Bel Riose'], 2],
                           [['Onum Barr'], ['Fie'], 1],
                           [['Bel Riose'], ['Fie'], 3],
                           [['Brodrig'], ['Bel Riose'], 5],
                           [['First Foundation'], ['Onum Barr'], 14],
                           [['Onum Barr'], ['Brodrig'], 6],
                           [['Brodrig'], ['Ducem Barr'], 1],
                           [['Ducem Barr'], ['Hari Seldon'], 2],
                           [['Hari Seldon'], ['Onum Barr'], 6],
                           [['First Foundation'], ['Ducem Barr'], 3],
                           [['Brodrig'], ['Hari Seldon'], 1],
                           [['Ducem Barr'], ['Galactic Empire'], 1],
                           [['Onum Barr'], ['Sennett Forell'], 9],
                           [['Onum Barr'], ['Second Foundation'], 1],
                           [['Second Foundation'], ['First Foundation'], 334],
                           [['First Foundation'], ['Toran Darell'], 29],
                           [['Toran Darell'], ['Bayta Darell'], 81],
                           [['Randu'], ['Toran Darell'], 2],
                           [['Toran Darell'], ['Fran'], 5],
                           [['Fran'], ['Randu'], 11],
                           [['Toran Darell'], ['Fie'], 4],
                           [['Fie'], ['Fran'], 1],
                           [['Bayta Darell'], ['Randu'], 3],
                           [['Hari Seldon'], ['Bayta Darell'], 9],
                           [['Fran'], ['Hari Seldon'], 1],
                           [['Bayta Darell'], ['Galactic Empire'], 4],
                           [['Hari Seldon'], ['Randu'], 2],
                           [['Toran Darell'], ['Hari Seldon'], 5],
                           [['Bayta Darell'], ['Second Empire'], 2],
                           [['Second Empire'], ['Fran'], 1],
                           [['Fran'], ['Bayta Darell'], 1],
                           [['Bayta Darell'], ['First Foundation'], 19],
                           [['Fran'], ['Hober Mallow'], 1],
                           [['First Foundation'], ['Randu'], 10],
                           [['First Foundation'], ['Fran'], 5],
                           [['Bel Riose'], ['Plan'], 4],
                           [['Toran Darell'], ['Mule'], 23],
                           [['Mule'], ['Randu'], 16],
                           [['Indbur'], ['First Foundation'], 13],
                           [['Indbur'], ['Han Pritcher'], 6],
                           [['Han Pritcher'], ['First Foundation'], 25],
                           [['Hari Seldon'], ['Indbur'], 2],
                           [['Fie'], ['First Foundation'], 18],
                           [['Flan Pritcher'], ['Han Pritcher'], 44],
                           [['Flan Pritcher'], ['First Foundation'], 11],
                           [['Indbur'], ['Fie'], 2],
                           [['Fie'], ['Personal Capsule'], 1],
                           [['Personal Capsule'], ['Flan Pritcher'], 6],
                           [['Mule'], ['Bayta Darell'], 30],
                           [['First Foundation'], ['Mule'], 135],
                           [['Toran Darell'], ['Magnifico Giganticus'], 25],
                           [['Magnifico Giganticus'], ['Mule'], 34],
                           [['Magnifico Giganticus'], ['Bayta Darell'], 48],
                           [['First Foundation'], ['Magnifico Giganticus'], 4],
                           [['Mule'], ['Han Pritcher'], 33],
                           [['Han Pritcher'], ['Toran Darell'], 5],
                           [['Ebling Mis'], ['First Foundation'], 33],
                           [['Ebling Mis'], ['Indbur'], 22],
                           [['Hari Seldon'], ['Ebling Mis'], 8],
                           [['Ebling Mis'], ['Han Pritcher'], 18],
                           [['Iwo'], ['Fran'], 3],
                           [['Fran'], ['Mule'], 2],
                           [['Randu'], ['Mangin'], 8],
                           [['Mule'], ['Mangin'], 3],
                           [['Randu'], ['Fie'], 1],
                           [['Mule'], ['Fie'], 18],
                           [['First Foundation'], ['Ovall Gri'], 4],
                           [['Ovall Gri'], ['Randu'], 6],
                           [['Indbur'], ['Mangin'], 1],
                           [['Mule'], ['Ovall Gri'], 2],
                           [['Ebling Mis'], ['Bayta Darell'], 30],
                           [['Magnifico Giganticus'], ['Ebling Mis'], 29],
                           [['Mule'], ['Ebling Mis'], 25],
                           [['Indbur'], ['Hober Mallow'], 3],
                           [['Indbur'], ['Mule'], 8],
                           [['Randu'], ['Indbur'], 3],
                           [['Hari Seldon'], ['Mule'], 27],
                           [['Magnifico Giganticus'], ['Indbur'], 2],
                           [['Han Pritcher'], ['Bayta Darell'], 13],
                           [['Indbur'], ['Bayta Darell'], 1],
                           [['Ebling Mis'], ['Randu'], 10],
                           [['Hella'], ['Mule'], 2],
                           [['Toran Darell'], ['Ebling Mis'], 39],
                           [['Hari Seldon'], ['Second Foundation'], 24],
                           [['Han Pritcher'], ['Fox'], 2],
                           [['Mule'], ['Fox'], 2],
                           [['Fox'], ['Fie'], 2],
                           [['Magnifico Giganticus'], ['Han Pritcher'], 1],
                           [['Jord Fara'], ['Jord Commason'], 2],
                           [['Mule'], ['Jord Commason'], 4],
                           [['Jord Commason'], ['First Foundation'], 5],
                           [['Jord Commason'], ['Personal Capsule'], 2],
                           [['Jord Commason'], ['Magnifico Giganticus'], 3],
                           [['Ebling Mis'], ['Fie'], 1],
                           [['Lee Senter'], ['Ebling Mis'], 1],
                           [['Mule'], ['Second Foundation'], 45],
                           [['Second Foundation'], ['Ebling Mis'], 15],
                           [['Second Foundation'], ['Bayta Darell'], 3],
                           [['Toran Darell'], ['Second Foundation'], 3],
                           [['Galactic Empire'], ['Mule'], 13],
                           [['Mule'], ['Second Empire'], 1],
                           [['Hari Seldon'], ['First Empire'], 2],
                           [['Encyclopedia Foundation'], ['Mule'], 4],
                           [['Flan Pritcher'], ['Mule'], 6],
                           [['Galactic Empire'], ['Han Pritcher'], 2],
                           [['Mule'], ['Bail Channis'], 47],
                           [['Bail Channis'], ['Second Foundation'], 26],
                           [['Fie'], ['Han Pritcher'], 5],
                           [['Flan Pritcher'], ['Fie'], 1],
                           [['Han Pritcher'], ['Hari Seldon'], 1],
                           [['Fie'], ['Second Foundation'], 11],
                           [['First Foundation'], ['Bail Channis'], 31],
                           [['First Speaker'], ['Mule'], 14],
                           [['First Speaker'], ['Fie'], 3],
                           [['Han Pritcher'], ['Bail Channis'], 37],
                           [['Second Foundation'], ['Han Pritcher'], 5],
                           [['Second Foundation'], ['Galactic Empire'], 3],
                           [['Bail Channis'], ['Flan Pritcher'], 1],
                           [['Flan Pritcher'], ['Second Foundation'], 1],
                           [['Bail Channis'], ['Fie'], 10],
                           [['Elders'], ['Han Pritcher'], 3],
                           [['Elders'], ['Bail Channis'], 4],
                           [['First Foundation'], ['Elders'], 1],
                           [['Mule'], ['Elders'], 1],
                           [['Plan'], ['Second Empire'], 5],
                           [['Second Empire'], ['Second Foundation'], 1],
                           [['Bail Channis'], ['First Speaker'], 15],
                           [['First Foundation'], ['First Speaker'], 18],
                           [['First Speaker'], ['Second Foundation'], 7],
                           [['Plan'], ['Second Foundation'], 5],
                           [['Bail Channis'], ['Ebling Mis'], 1],
                           [['Arcadia Darell'], ['Arkady Darell'], 4],
                           [['Arkady Darell'], ['Bayta Darell'], 6],
                           [['Plan'], ['Arkady Darell'], 2],
                           [['Galactic Empire'], ['Plan'], 5],
                           [['Hober Mallow'], ['Plan'], 4],
                           [['Mule'], ['Plan'], 4],
                           [['Plan'], ['Fie'], 8],
                           [['Hari Seldon'], ['Arcadia Darell'], 3],
                           [['Toran Darell'], ['Pelleas Anthor'], 1],
                           [['Plan'], ['Arcadia Darell'], 4],
                           [['Hari Seldon'], ['First Speaker'], 6],
                           [['First Speaker'], ['Student'], 17],
                           [['Hari Seldon'], ['Student'], 3],
                           [['First Speaker'], ['Plan'], 13],
                           [['Student'], ['Mule'], 2],
                           [['Student'], ['Plan'], 3],
                           [['First Speaker'], ['Second Empire'], 1],
                           [['First Foundation'], ['Student'], 2],
                           [['Pelleas Anthor'], ['Jole Turbor'], 6],
                           [['Jole Turbor'], ['Elvett Semic'], 9],
                           [['Jole Turbor'], ['Homir Munn'], 17],
                           [['Homir Munn'], ['Elvett Semic'], 7],
                           [['Pelleas Anthor'], ['Kleise'], 5],
                           [['Jole Turbor'], ['Kleise'], 1],
                           [['Kleise'], ['Homir Munn'], 1],
                           [['Homir Munn'], ['Pelleas Anthor'], 17],
                           [['Kleise'], ['Bayta Darell'], 1],
                           [['Elvett Semic'], ['Kleise'], 2],
                           [['Jole Turbor'], ['Second Foundation'], 7],
                           [['Jole Turbor'], ['First Foundation'], 10],
                           [['First Foundation'], ['Kleise'], 4],
                           [['Kleise'], ['Second Foundation'], 6],
                           [['First Foundation'], ['Homir Munn'], 24],
                           [['Flomir Munn'], ['Homir Munn'], 11],
                           [['Mule'], ['Stettin'], 8],
                           [['Pelleas Anthor'], ['Second Foundation'], 7],
                           [['First Foundation'], ['Pelleas Anthor'], 15],
                           [['Homir Munn'], ['Fie'], 6],
                           [['Second Foundation'], ['Student'], 2],
                           [['Pelleas Anthor'], ['Arcadia Darell'], 8],
                           [['Arcadia Darell'], ['Homir Munn'], 27],
                           [['Homir Munn'], ['Arkady Darell'], 1],
                           [['Stettin'], ['Callia'], 14],
                           [['Lev Meirus'], ['Callia'], 3],
                           [['Poochie'], ['Callia'], 8],
                           [['First Foundation'], ['Callia'], 6],
                           [['Callia'], ['Mule'], 3],
                           [['Mule'], ['Poochie'], 1],
                           [['Mule'], ['Lev Meirus'], 2],
                           [['Lev Meirus'], ['First Foundation'], 2],
                           [['Lev Meirus'], ['Second Foundation'], 1],
                           [['First Foundation'], ['Stettin'], 14],
                           [['Hari Seldon'], ['Homir Munn'], 13],
                           [['Homir Munn'], ['Mule'], 14],
                           [['Plan'], ['Homir Munn'], 2],
                           [['Lev Meirus'], ['Poochie'], 1],
                           [['First Foundation'], ['Poochie'], 1],
                           [['Arcadia Darell'], ['First Foundation'], 10],
                           [['Callia'], ['Arcadia Darell'], 18],
                           [['Homir Munn'], ['Callia'], 10],
                           [['Poochie'], ['Homir Munn'], 1],
                           [['Homir Munn'], ['Stettin'], 12],
                           [['Hari Seldon'], ['Callia'], 5],
                           [['Mule'], ['Arcadia Darell'], 8],
                           [['Galactic Empire'], ['Callia'], 1],
                           [['Mule'], ['Kleise'], 1],
                           [['Fie'], ['Pelleas Anthor'], 4],
                           [['Stettin'], ['Flomir Munn'], 2],
                           [['Flomir Munn'], ['Mule'], 2],
                           [['Stettin'], ['Fie'], 2],
                           [['Second Foundation'], ['Arkady Darell'], 1],
                           [['Arkady Darell'], ['Mule'], 1],
                           [['Bayta Darell'], ['Homir Munn'], 1],
                           [['Arcadia Darell'], ['Stettin'], 2],
                           [['Arcadia Darell'], ['Pappa'], 15],
                           [['Mamma'], ['Pappa'], 22],
                           [['Callia'], ['Mamma'], 2],
                           [['Pappa'], ['First Foundation'], 2],
                           [['Pappa'], ['Stettin'], 1],
                           [['Arcadia Darell'], ['Mamma'], 3],
                           [['Callia'], ['Second Foundation'], 3],
                           [['Pappa'], ['Preem Palver'], 1],
                           [['Preem Palver'], ['Arcadia Darell'], 7],
                           [['Elvett Semic'], ['Fie'], 3],
                           [['Elvett Semic'], ['Pelleas Anthor'], 8],
                           [['Hober Mallow'], ['Pelleas Anthor'], 1],
                           [['Bayta Darell'], ['Arcadia Darell'], 1],
                           [['Fie'], ['Arcadia Darell'], 4],
                           [['Arcadia Darell'], ['Second Foundation'], 1],
                           [['Homir Munn'], ['Second Foundation'], 5],
                           [['Preem Palver'], ['Arkady Darell'], 1],
                           [['Preem Palver'], ['Mamma'], 1],
                           [['First Foundation'], ['Mamma'], 3],
                           [['Stettin'], ['Second Foundation'], 3],
                           [['Plan'], ['Jole Turbor'], 1],
                           [['Preem Palver'], ['Jole Turbor'], 4],
                           [['First Foundation'], ['Preem Palver'], 1],
                           [['Homir Munn'], ['Lev Meirus'], 2],
                           [['Hari Seldon'], ['Pelleas Anthor'], 7],
                           [['Flomir Munn'], ['Fie'], 4],
                           [['First Foundation'], ['Elvett Semic'], 1],
                           [['Elvett Semic'], ['Second Foundation'], 1],
                           [['Flomir Munn'], ['Pelleas Anthor'], 2],
                           [['Callia'], ['Pelleas Anthor'], 1],
                           [['Jole Turbor'], ['Mule'], 1],
                           [['First Speaker'], ['Arcadia Darell'], 1],
                           [['Preem Palver'], ['First Speaker'], 3]]

    return connection_list
